name: Deploy with Secret
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace token in index.html
        run: |
          sed -i "s/__BOT_TOKEN__/${{ secrets.MY_SECRET_TOKEN }}/g" index.html

      - name: Deploy (Example: Push to GitHub Pages)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update token"
          git push
